---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: git-repo
      vars:
        git_repo_directory: /var/local/repos
        git_repo_name: repo_name
        git_repo_post_update_hook: true
        git_repo_update_hook: true
