---
- name: Converge
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: git-repo
      vars:
        git_repo_directory: /var/local/repos
        git_repo_name: repo_name
        git_server_restart_command: "echo nothing > /dev/null"
